FROM gradle:7.5.1-jdk-focal as builder

USER root

ENV APP_DIR /app
WORKDIR $APP_DIR

COPY build.gradle.kts $APP_DIR/
COPY settings.gradle.kts $APP_DIR/

COPY .. $APP_DIR

RUN gradle build

USER guest

# -----------------------------------------------------------------------------

FROM amazoncorretto:17.0.5-al2

ARG SERVER_PORT=8080

WORKDIR /app

COPY --from=builder /app/build/libs/crqs-command-*-SNAPSHOT.jar /app/crqs-command.jar

EXPOSE ${SERVER_PORT}

ENTRYPOINT ["java", "-jar", "crqs-command.jar"]