server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: ~

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cqrs?user=postgres&password=test}
  flyway:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      security.retries: 3
      security.max.block.ms: 5000
      security.max.in.flight.requests.per.connection: 1
    consumer:
      group-id: cqrs
      auto-offset-reset: earliest
      max-poll-records: 50

